file = open("test.txt","r")
print(file.read())
file.seek(0)
print(file.read())
file.close()
file = open("test.txt","r")
print(file.tell())
file.read(5)
print(file.tell())
file.close()
file = open("test.txt","r+")
file.truncate(5)
file.close()
file = open("demo.txt","w")
file.write("python programming")
file.truncate(6)
file.close()
add = lambda a,b: a+b
print(add(2,3))

