tup = (1,2,3,4)
name = ("anamika","golu","shivagi")
print(tup)
print(name)
print(name[0])
print(name[1])
print(name[-1])
nums = (10,20,30,40)
print(nums[1:4])
country = ("spain","india","italy","england","germany")
if "germany" in country:
    print("germany is persent.")
else:
    print("germany")
animals = ("cat","dog","goat","pig","ox","donkey","monkey")
print(animals[3:5])
print(animals[-7:-2])
print(animals[4:])
print(animals[-4:])
print(animals[:3])
print(animals[:-4])
print(animals[::2])
print(animals[-5:-1:2])
nums = (1,2,3,4,4)
print(nums.count(2))
nums = (10,20,30)
print(nums.index(20))
tup = (1,2,3,4)
lst = list(tup)
lst[0] = 10
tup = tuple(lst)
print(tup)
a = (1,2)
b = (3,4)
c = a+b
print(c)
tup = ("hi",) * 3
print(tup)
nums = (1,2,3)
print(2 in nums)
print(5 in nums)
tup = (10,20,30)
a,b,c = tup
print(a)
print(b)
print(c)
tup = (1,2,3,4)
print(len(tup))
tup = ((1,2),(3,4),())
print(tup[1])